Merged PR 155: Address review comments. Use origin/private prefix.
Address review comments. Use origin/private prefix.

Related work items: #271

diff --git a/Tools/hooks/commit-msg b/Tools/hooks/commit-msg
--- a/Tools/hooks/commit-msg
+++ b/Tools/hooks/commit-msg
@@ -1,6 +1,6 @@
 #!/bin/sh
 
-disallowed=$(git show private:disallowed.txt) || { echo "$0 could not read disallowed file"; exit 1; }
+disallowed=$(git show origin/private:disallowed.txt) || { echo "$0 could not read disallowed file"; exit 1; }
 
 if grep -wiE "$disallowed" "$1"; then
     echo "Aborting - commit message matches $disallowed"
diff --git a/Tools/hooks/pre-commit b/Tools/hooks/pre-commit
--- a/Tools/hooks/pre-commit
+++ b/Tools/hooks/pre-commit
@@ -8,10 +8,7 @@ else
 	against=$(git hash-object -t tree /dev/null)
 fi
 
-# Redirect output to stderr.
-exec 1>&2
-
-disallowed=$(git show private:disallowed.txt) || { echo "$0 could not read disallowed file"; exit 1; }
+disallowed=$(git show origin/private:disallowed.txt) || { echo "$0 could not read disallowed file"; exit 1; }
 
 # GREP full Word, Ignore case, Extended regex
 if git diff --cached "$against" | grep -wiE "$disallowed"; then
